//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package sql

import (
	"fmt"

	"github.com/icha-senpai/note/third_party/forks/lute/ast"
	"github.com/icha-senpai/note/kernel/av"
	"github.com/icha-senpai/note/kernel/util"
)

func RenderAttributeViewTable(attrView *av.AttributeView, view *av.View, query string, depth *int, cachedAttrViews map[string]*av.AttributeView, ignoreRows bool) (ret *av.Table) {
	viewable := attrView.RenderedViewables[view.ID]
	if nil != viewable {
		ret = viewable.(*av.Table)
		return
	}

	ret = &av.Table{
		BaseInstance: av.NewViewBaseInstance(view),
		Columns:      []*av.TableColumn{},
		Rows:         []*av.TableRow{},
	}

	for _, col := range view.Table.Columns {
		key, getErr := attrView.GetKey(col.ID)
		if nil != getErr {

			if !ignoreRows {
				removeMissingField(attrView, view, col.ID)
			}
			continue
		}

		ret.Columns = append(ret.Columns, &av.TableColumn{
			BaseInstanceField: &av.BaseInstanceField{
				ID:           key.ID,
				Name:         key.Name,
				Type:         key.Type,
				Icon:         key.Icon,
				Wrap:         col.Wrap,
				Hidden:       col.Hidden,
				Desc:         key.Desc,
				Calc:         col.Calc,
				Options:      key.Options,
				NumberFormat: key.NumberFormat,
				Template:     key.Template,
				Relation:     key.Relation,
				Rollup:       key.Rollup,
				Date:         key.Date,
				Created:      key.Created,
				Updated:      key.Updated,
			},
			Width: col.Width,
			Pin:   col.Pin,
			Align: col.Align,
		})
	}

	if ignoreRows {
		return
	}

	rowsValues := generateAttrViewItems(attrView, view)
	filterNotFoundAttrViewItems(rowsValues)

	for rowID, rowValues := range rowsValues {

		kvByCol := map[string]*av.KeyValues{}
		for _, keyValues := range rowValues {
			if _, ok := kvByCol[keyValues.Key.ID]; !ok {
				kvByCol[keyValues.Key.ID] = keyValues
			}
		}

		var tableRow av.TableRow
		for _, col := range ret.Columns {
			var tableCell *av.TableCell
			if keyValues, ok := kvByCol[col.ID]; ok {
				tableCell = &av.TableCell{
					BaseValue: &av.BaseValue{
						ID:        keyValues.Values[0].ID,
						Value:     keyValues.Values[0],
						ValueType: col.Type,
					},
				}
			}
			if nil == tableCell {
				tableCell = &av.TableCell{
					BaseValue: &av.BaseValue{
						ID:        rowID[:14] + ast.NewNodeID()[14:],
						ValueType: col.Type,
					},
				}
			}
			tableRow.ID = rowID

			filedDateIsTime := false
			if nil != col.Date {
				filedDateIsTime = col.Date.FillSpecificTime
			}
			fillAttributeViewBaseValue(tableCell.BaseValue, col.ID, rowID, col.NumberFormat, col.Template, filedDateIsTime)
			tableRow.Cells = append(tableRow.Cells, tableCell)
		}
		ret.Rows = append(ret.Rows, &tableRow)
	}

	fillAttributeViewKeyValues(attrView, ret)

	var ialIDs []string
	for _, row := range ret.Rows {
		blockVal := row.GetBlockValue()
		if nil != blockVal && !blockVal.IsDetached {
			ialIDs = append(ialIDs, blockVal.Block.ID)
		}
	}
	ials := BatchGetBlockAttrs(ialIDs)

	fillAttributeViewAutoGeneratedValues(attrView, ret, ials, depth, cachedAttrViews)

	renderTemplateErr := fillAttributeViewTemplateValues(attrView, view, ret, ials)
	if nil != renderTemplateErr {
		util.PushErrMsg(fmt.Sprintf(util.Langs[util.Lang][44], util.EscapeHTML(renderTemplateErr.Error())), 30000)
	}

	filterByQuery(query, ret)
	manualSort(view, ret)
	return
}
